### ISSUE TITLE
get_network_strength fails when getting SignalStrength

### ISSUE THREAD

**Issue by vanillagorillaa** [commaai/openpilot#1220]
> Result: Parcel(00000000    '....')                                         
Error getting network status                                               
Traceback (most recent call last):                                         
  File "/data/openpilot/selfdrive/thermald.py", line 202, in thermald_thread                                                                           
    network_strength = get_network_strength(network_type)                                                                                              
  File "/data/openpilot/common/android.py", line 240, in get_network_strength                                                                          
    lvl = int(arr[53][:-2])                                                
ValueError: invalid literal for int() with base 10: 'WI' 

Changing networks causes the parsing of `dumpsys connectivity` to not always output the desired `SignalStrength`. Tried on two networks and got `Transport` and `Wi`.

**Comment by vanillagorillaa** [comment]
Looks to be fixed with 8eff974a417f58b6c5ce953ef1e903a68feeff70 , closing
