### ISSUE TITLE
class PowerMonitoring  has synchronization problem.

### ISSUE THREAD

**Issue by deanlee** [commaai/openpilot#1384]
Thread synchronization problem in PowerMonitoring:
self.power_used_uWh might be a negative value, cause capnp to thrown a typeerror (offroadPowerUsage is Uint32) 
https://github.com/commaai/openpilot/blob/d39595cf10a7813e55139320daa252278dd7567d/selfdrive/thermald/power_monitoring.py#L150-L162

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/openpilot/selfdrive/launcher.py", line 20, in launcher
    mod.main()
  File "/data/openpilot/selfdrive/thermald/thermald.py", line 454, in main
    thermald_thread()
  File "/data/openpilot/selfdrive/thermald/thermald.py", line 423, in thermald_thread
    msg.thermal.offroadPowerUsage = pm.get_power_used()
  File "capnp/lib/capnp.pyx", line 1274, in capnp.lib.capnp._DynamicStructBuilder.__setattr__
  File "capnp/lib/capnp.pyx", line 1272, in capnp.lib.capnp._DynamicStructBuilder.__setattr__
  File "capnp/lib/capnp.pyx", line 1265, in capnp.lib.capnp._DynamicStructBuilder._set
  File "capnp/lib/capnp.pyx", line 715, in capnp.lib.capnp._setDynamicField
capnp.lib.capnp.KjException: capnp/dynamic.c++:1675: failed: expected value >= 0 && T(value) == value; Value out-of-range for requested type.; value = -5330

**Comment by robbederks** [comment]
From the logs, this never seems to happen on our official devices, only rarely on frEONs.
My suspicion is on the OnePlus 3T with batteryless mods.
Have added a sanity check now though: #1390

**Comment by deanlee** [comment]
my device is LeEco Le Pro 3
