### ISSUE TITLE
ImportError: No module named opendbc

### ISSUE THREAD

**Issue by Capri2014** [commaai/openpilot#144]
This is what I've got by running `/.run_docker_test.sh`, seems like the PYTHONPATH was not set right?
```
Successfully built b4ab4237c798
Successfully tagged tmppilot:latest
Traceback (most recent call last):
  File "./test_longitudinal.py", line 14, in <module>
    from selfdrive.test.plant.maneuver import Maneuver
  File "/tmp/openpilot/selfdrive/test/plant/maneuver.py", line 4, in <module>
    from plant import Plant
  File "/tmp/openpilot/selfdrive/test/plant/plant.py", line 8, in <module>
    from opendbc import DBC_PATH
ImportError: No module named opendbc
```

**Comment by energee** [comment]
Run `git submodule update --init --recursive`, I hear they moving to git subtrees on next release.

**Comment by Capri2014** [comment]
@energee  Thanks! It works!
