### ISSUE TITLE
modeld crashes when running Carla simulation

### ISSUE THREAD

**Issue by daulet** [commaai/openpilot#1655]
**Describe the bug**
modeld crashes expecting non-empty input from stdin when running Carla simulation.

**How to reproduce or log data**
Follow steps from [tools/sim/README](https://github.com/commaai/openpilot/blob/master/tools/sim/README.md)

**Expected behavior**
Openpilot works with Carla

**Device/Version information (please complete the following information):**
Ubuntu 18.04

**Additional context**
keras_runner receives an empty input from stdin and fails:

Traceback (most recent call last):                                                                 
  File "/home/dake/openpilot/selfdrive/modeld/runners/keras_runner.py", line 49, in <module> 
    run_loop(m)
  File "/home/dake/openpilot/selfdrive/modeld/runners/keras_runner.py", line 32, in run_loop
    inputs.append(read(ts).reshape(shp))
  File "/home/dake/openpilot/selfdrive/modeld/runners/keras_runner.py", line 16, in read
    assert(len(st) > 0)
AssertionError

**Comment by ed2k** [comment]
It is the zmq problem in ubuntu 18.04, signature `src/mailbox.cpp:99 assertion`.  workaround is to rebuild libzmq with g++-6
