### ISSUE TITLE
Manager failed to start on PC

### ISSUE THREAD

**Issue by johschmitz** [commaai/openpilot#1683]
**Describe the bug**
I get "Manager failed to start"

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
Pipfile: needs update
Pipfile.lock: needs update
{"event": "dirty comma branch", "version": "0.8", "dirty": true, "origin": "https://github.com/commaai/openpilot.git", "branch": "origin/master", "dirty_files": ":100644 100644 5fb643ad859eb1972783955128b9d75b88e80d7e 0000000000000000000000000000000000000000 M\tPipfile\n:100644 100644 e297d667e1d3ea203d67d622e4e1986571076e7f 0000000000000000000000000000000000000000 M\tPipfile.lock\n", "commit": "97b1ee25a7cff52216f5a1e8c5cb2b4b5847eba2", "origin_commit": "97b1ee25a7cff52216f5a1e8c5cb2b4b5847eba2"}
sh: 1: content: not found
call: unrecognized service
getting pilotauth
dongle id is 0a63b68feb9841df
dirty is 1
preimporting selfdrive.thermald.thermald
Building panda firmware
Manager failed to start
Traceback (most recent call last):
  File "./manager.py", line 611, in <module>
    main()
  File "./manager.py", line 588, in main
    manager_prepare(spinner)
  File "./manager.py", line 531, in manager_prepare
    prepare_managed_process(p)
  File "./manager.py", line 325, in prepare_managed_process
    importlib.import_module(proc)
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/schmitz/temp/openpilot/selfdrive/thermald/thermald.py", line 23, in <module>
    FW_SIGNATURE = get_expected_signature()
  File "/home/schmitz/temp/openpilot/selfdrive/pandad.py", line 24, in get_expected_signature
    fw_fn = get_firmware_fn()
  File "/home/schmitz/temp/openpilot/selfdrive/pandad.py", line 18, in get_firmware_fn
    build_st(fn, clean=False)
  File "/home/schmitz/temp/openpilot/panda/python/__init__.py", line 33, in build_st
    _ = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /home/schmitz/temp/openpilot/panda/python/../board && : && make -f Makefile obj/panda.bin' returned non-zero exit status 2.
Traceback (most recent call last):
  File "./manager.py", line 611, in <module>
    main()
  File "./manager.py", line 588, in main
    manager_prepare(spinner)
  File "./manager.py", line 531, in manager_prepare
    prepare_managed_process(p)
  File "./manager.py", line 325, in prepare_managed_process
    importlib.import_module(proc)
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/schmitz/temp/openpilot/selfdrive/thermald/thermald.py", line 23, in <module>
    FW_SIGNATURE = get_expected_signature()
  File "/home/schmitz/temp/openpilot/selfdrive/pandad.py", line 24, in get_expected_signature
    fw_fn = get_firmware_fn()
  File "/home/schmitz/temp/openpilot/selfdrive/pandad.py", line 18, in get_firmware_fn
    build_st(fn, clean=False)
  File "/home/schmitz/temp/openpilot/panda/python/__init__.py", line 33, in build_st
    _ = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/schmitz/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd /home/schmitz/temp/openpilot/panda/python/../board && : && make -f Makefile obj/panda.bin' returned non-zero exit status 2.
```

**How to reproduce or log data**
Steps to reproduce the behavior, or a explorer/cabana link to the exact drive and timestamp of when the bug occurred.

    $ pipenv install --dev
    $ pipenv shell
    (openpilot) $ cd selfdrive
    (openpilot) $ export PYTHONPATH=$HOME/temp/openpilot
    (openpilot) $ PASSIVE=0 NOBOARD=1 ./manager.py

**Expected behavior**
Manager should start according to https://github.com/commaai/openpilot/tree/master/tools/sim

**Device/Version information (please complete the following information):**
 - Device: PC
 - Dongle ID: 0a63b68feb9841df
 - Version: 0.8 (git master)

**Additional context**

Not sure why it wants to build the firmware although I am trying to run with NOBOARD=1. Do I need to install the whole ARM toolchain even if I just want to run it on my PC?

**Comment by johschmitz** [comment]
Alright it works if I DO install gcc-arm-none-eabi and libnewlib-arm-none-eabi but it is probably unnecessary.
