### ISSUE TITLE
scons -j4 error when trying to launch openpilot outside a docker for PC simulation

### ISSUE THREAD

**Issue by AIasd** [commaai/openpilot#20910]
Hi,

I am trying to run Openpilot in Carla outside of a docker by running `./launch_openpilot.sh` as well as `./bridge.py` in addition to the CARLA server.

I encountered the following error when I run  `./launch_openpilot.sh`:
```
{"event": "dirty comma branch", "version": "0.8.4", "dirty": true, "origin": "https://github.com/commaai/openpilot.git", "branch": "origin/master", "dirty_files": ":100755 100755 1ac31bcc3a54cac01cdb41b67ffb52f641f40c62 0000000000000000000000000000000000000000 M\ttools/ubuntu_setup.sh", "commit": "c4d00134ee18296ef4b498f2c1c623ffa3fda55f", "origin_commit": "c4d00134ee18296ef4b498f2c1c623ffa3fda55f"}
System time valid
starting process ui
preimporting selfdrive.locationd.calibrationd
preimporting selfdrive.controls.controlsd
./ui: 3: exec: ./_ui: not found
Manager failed to start
Traceback (most recent call last):
  File "./manager.py", line 200, in <module>
    main()
  File "./manager.py", line 175, in main
    manager_prepare()
  File "./manager.py", line 100, in manager_prepare
    p.prepare()
  File "/home/zhongzzy9/openpilot/selfdrive/manager/process.py", line 213, in prepare
    importlib.import_module(self.module)
  File "/home/zhongzzy9/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhongzzy9/openpilot/selfdrive/controls/controlsd.py", line 12, in <module>
    from selfdrive.boardd.boardd import can_list_to_can_capnp
  File "/home/zhongzzy9/openpilot/selfdrive/boardd/boardd.py", line 4, in <module>
    from selfdrive.boardd.boardd_api_impl import can_list_to_can_capnp
ModuleNotFoundError: No module named 'selfdrive.boardd.boardd_api_impl'
./text: 10: exec: ./qt/text: not found
^CTraceback (most recent call last):
  File "./manager.py", line 200, in <module>
    main()
  File "./manager.py", line 175, in main
    manager_prepare()
  File "./manager.py", line 100, in manager_prepare
    p.prepare()
  File "/home/zhongzzy9/openpilot/selfdrive/manager/process.py", line 213, in prepare
    importlib.import_module(self.module)
  File "/home/zhongzzy9/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhongzzy9/openpilot/selfdrive/controls/controlsd.py", line 12, in <module>
    from selfdrive.boardd.boardd import can_list_to_can_capnp
  File "/home/zhongzzy9/openpilot/selfdrive/boardd/boardd.py", line 4, in <module>
    from selfdrive.boardd.boardd_api_impl import can_list_to_can_capnp
ModuleNotFoundError: No module named 'selfdrive.boardd.boardd_api_impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manager.py", line 209, in <module>
    t.wait_for_exit()
  File "/home/zhongzzy9/openpilot/common/text_window.py", line 37, in wait_for_exit
    time.sleep(0.1)
```
After looking into th [this related issue](https://github.com/commaai/openpilot/issues/1358), the error might be caused by scons.

I tried to run `scons -j4` then and encountered the error as the following.
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
clang++ -o selfdrive/locationd/models/generated/loc_4.os -c -std=c++1z -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -fPIC -I. -Iphonelibs/catch2/include -Iphonelibs/bzip2 -Iphonelibs/libyuv/include -Iphonelibs/openmax/include -Iphonelibs/json11 -Iphonelibs/curl/include -Iphonelibs/libgralloc/include -Iphonelibs/android_frameworks_native/include -Iphonelibs/android_hardware_libhardware/include -Iphonelibs/android_system_core/include -Iphonelibs/linux/include -Iphonelibs/snpe/include -Iphonelibs/nanovg -Iphonelibs/qrcode -Iphonelibs -Icereal -Icereal/messaging -Icereal/visionipc -Iopendbc/can -Iphonelibs/json11 selfdrive/locationd/models/generated/loc_4.cpp
clang++ -o selfdrive/boardd/boardd -Wl,--as-needed -Wl,-rpath=/home/zhongzzy9/openpilot/phonelibs/snpe/x86_64-linux-clang -Wl,-rpath=/home/zhongzzy9/openpilot/cereal -Wl,-rpath=/home/zhongzzy9/openpilot/selfdrive/common selfdrive/boardd/boardd.o selfdrive/boardd/panda.o selfdrive/boardd/pigeon.o -Lphonelibs/snpe/x86_64-linux-clang -Lphonelibs/libyuv/x64/lib -Lcereal -Lselfdrive/common -L/usr/lib -L/usr/local/lib -Lcereal -Lphonelibs -Lopendbc/can -Lselfdrive/boardd -Lselfdrive/common -lusb-1.0 selfdrive/common/libcommon.a -ljson11 cereal/libcereal.a cereal/libmessaging.a -lpthread -lzmq -lcapnp -lkj
ar rc selfdrive/boardd/libcan_list_to_can_capnp.a selfdrive/boardd/can_list_to_can_capnp.o
ranlib selfdrive/boardd/libcan_list_to_can_capnp.a
clang++ -o selfdrive/camerad/main.o -c -std=c++1z -g -fPIC -O2 -Wunused -Werror -Wno-unknown-warning-option -Wno-deprecated-register -Wno-register -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-reorder-init-list -I. -Iphonelibs/catch2/include -Iphonelibs/bzip2 -Iphonelibs/libyuv/include -Iphonelibs/openmax/include -Iphonelibs/json11 -Iphonelibs/curl/include -Iphonelibs/libgralloc/include -Iphonelibs/android_frameworks_native/include -Iphonelibs/android_hardware_libhardware/include -Iphonelibs/android_system_core/include -Iphonelibs/linux/include -Iphonelibs/snpe/include -Iphonelibs/nanovg -Iphonelibs/qrcode -Iphonelibs -Icereal -Icereal/messaging -Icereal/visionipc -Iopendbc/can -Iphonelibs/json11 selfdrive/camerad/main.cc
clang++ -o selfdrive/boardd/boardd_api_impl.so -pthread -shared -Wl,-rpath=/home/zhongzzy9/openpilot/phonelibs/snpe/x86_64-linux-clang -Wl,-rpath=/home/zhongzzy9/openpilot/cereal -Wl,-rpath=/home/zhongzzy9/openpilot/selfdrive/common selfdrive/boardd/boardd_api_impl.o -Lphonelibs/snpe/x86_64-linux-clang -Lphonelibs/libyuv/x64/lib -Lcereal -Lselfdrive/common -L/usr/lib -L/usr/local/lib -Lcereal -Lphonelibs -Lopendbc/can -Lselfdrive/boardd -Lselfdrive/common -lcan_list_to_can_capnp -lcapnp -lkj
cereal/libmessaging.a(socketmaster.os): In function `SubMaster::SubMessage::~SubMessage()':
/home/zhongzzy9/openpilot/cereal/messaging/socketmaster.cc:39: undefined reference to `AlignedBuffer::~AlignedBuffer()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [selfdrive/boardd/boardd] Error 1
scons: building terminated because of errors.
```

I checked the file `socketmaster.cc` as well as `messaging.h`, it looks that `AlignedBuffer` was defined in `messaging.h` already so I am quite confused why it reports the error of undefined reference.

Any help will be appreciated!

**Comment by adeebshihadeh** [comment]
Our issue tracker isn't the right place to get help building openpilot. Try our [discord](https://discor.comma.ai). Though,  you should ensure that you're using Ubuntu 20.04 and have all the dependencies and environment properly set up.
