### ISSUE TITLE
cereal.messaging.messaging_pyx.MultiplePublishersError when attempting to replay (ui/replay)

### ISSUE THREAD

**Issue by zorrobyte** [commaai/openpilot#21131]
**Describe the bug**

Trying to run manager, controls results in a `cereal.messaging.messaging_pyx.MultiplePublishersError` when using new replay tool (ui/replay)

**How to reproduce or log data**

~/openpilot/selfdrive/ui/replay$ ./replay "0982d79ebb0de295|2021-01-17--17-13-08"

*new tab*

~/openpilot/selfdrive/controls$ ./controlsd.py == cereal.messaging.messaging_pyx.MultiplePublishersError

~/openpilot/selfdrive/manager$ ./manager.py == cereal.messaging.messaging_pyx.MultiplePublishersError

**Additional context**

Traceback (most recent call last):
  File "./controlsd.py", line 651, in <module>
    main()
  File "./controlsd.py", line 647, in main
    controls.controlsd_thread()
  File "./controlsd.py", line 641, in controlsd_thread
    self.step()
  File "./controlsd.py", line 636, in step
    self.publish_logs(CS, start_time, actuators, v_acc, a_acc, lac_log)
  File "./controlsd.py", line 583, in publish_logs
    self.pm.send('controlsState', dat)
  File "/home/ross/openpilot/cereal/messaging/__init__.py", line 244, in send
    self.sock[s].send(dat)
  File "cereal/messaging/messaging_pyx.pyx", line 149, in cereal.messaging.messaging_pyx.PubSocket.send
cereal.messaging.messaging_pyx.MultiplePublishersError

This worked on geo's livestream, so something broke: https://youtu.be/ixfAdv9sL30?t=2798

**Comment by adeebshihadeh** [comment]
When running a replay with all the messages, you only want to run UI, not all of manager. You're seeing that because replay opens all the pub sockets to replay the messages, but manager also starts the daemons that normally send those messages.
