### ISSUE TITLE
Zygote restart due to phone services crashing

### ISSUE THREAD

**Issue by nabeelr** [commaai/openpilot#21539]
**Describe the bug**

While OP was driving on road, I got a red screen saying that there was an issue communicating between processes. OP continued to navigate for a couple more seconds before disengaging itself. I was able to immediately re-engage a few seconds later. After driving for a bit longer, the image on my C2 rotated upside down, however all seemed to keep working. A few more seconds later, the image froze entirely and the C2 became totally unresponsive, with no visual or auditory prompts. OP would still silently engage drive the car, however when cruise control was engaged. After a few minutes of driving, the image flashed and started working again and a few seconds later rotated back into the normal position.

**How to reproduce or log data**

Just drove for a few hours. Not sure how reproducible it is.

**Device/Version information (please complete the following information):**
 - Device: comma two
 - Dongle ID: a8149c07cf2713da
 - Route: a8149c07cf2713da|2021-07-09--21-59-15--86
 - Timestamp: Red screen at approximately 23:26:02, Image flipped at approximately 23:32:45, interface froze at approximately 23:33:35, interface unfroze and rotated back to normal at approximately 23:41:35
 - Version: master-ci fa9f92a7ce98605ec1c373b39bd72c4a268e7239
 - Car make/model: 2019 Manual Golf R

**Additional context**

The next drive the C2 complained about GPS reception. Not sure if this is related or not, as the C2 was not rebooted between uhhh drives.

Let me know if any extra info is needed or if there is any tested you'd like me to do. ;)

**Comment by adeebshihadeh** [comment]
One of the cellular daemons that system server considers critical crashed, causing Zygote to be restarted.

```
6: (0/446): RIL[0][ims_socket0] void qcril_qmi_ims_socket_agent::recv_thread_handler(): recv failed. recv_byte_num: 0. closing the socket.

5: Scheduling restart of crashed service org.codeaurora.ims/.ImsService in 1000ms

5: Scheduling restart of crashed service com.android.phone/.TelephonyDebugService in 0ms

5: Scheduling restart of crashed service com.qti.qualcomm.datastatusnotification/.DataStatusNotificationService in 10998ms

5: Re-adding persistent process ProcessRecord{3ec8722 1550:com.android.phone/1001}

6: Starting VM process through Zygote failed

6: Failure starting process com.android.phone
java.lang.RuntimeException: Starting VM process through Zygote failed
	at android.os.Process.start(Process.java:499)
	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3601)
	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3449)
	at com.android.server.am.ActivityManagerService.cleanUpApplicationRecordLocked(ActivityManagerService.java:16091)
	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4816)
	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4985)
	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1358)
	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
Caused by: android.os.ZygoteStartFailedEx: java.io.EOFException
	at android.os.Process.zygoteSendArgsAndGetResult(Process.java:590)
	at android.os.Process.startViaZygote(Process.java:710)
	at android.os.Process.start(Process.java:493)
	... 7 more
Caused by: java.io.EOFException
	at libcore.io.Streams.readFully(Streams.java:83)
	at java.io.DataInputStream.readInt(DataInputStream.java:103)
	at android.os.Process.zygoteSendArgsAndGetResult(Process.java:581)
	... 9 more
```
