### ISSUE TITLE
Panda reconnect failed

### ISSUE THREAD

**Issue by XinnWang** [commaai/openpilot#21985]
**Describe the bug**

I'm running openpilot inside ghcr.io/commaai/openpilot-sim:latest on my pc, using Panda to connect with my toyota corolla.

**How to reproduce or log data**

Command
```
cd /openpilot/selfdrive/manager
PASSIVE=0 NOSENSOR=1 USE_WEBCAM=1 ./manager.py
``` 
Log
```
...
Connecting to panda
Panda found, connecting
opening device 2a0021000751393038373731 0xddcc
connected
Panda None connected, version: DEV-unknown-DEBUG, signature 11da788485aa9614a2eb0bc3e43640c7eba639358049db9272dee995aa4540f920d39787d332d9fb9633083916f6b578b7b058817f0281d514d47baa5a2755582fa2ac1f41a18f6a33a3eb6f70c8888a2b65932979956220161f78766d39f92462c9ea969e3aeef1085fd42ae3670dddd01d3f86fd968e32d204ba7e6e6d8f47, expected 11da788485aa9614a2eb0bc3e43640c7eba639358049db9272dee995aa4540f920d39787d332d9fb9633083916f6b578b7b058817f0281d514d47baa5a2755582fa2ac1f41a18f6a33a3eb6f70c8888a2b65932979956220161f78766d39f92462c9ea969e3aeef1085fd42ae3670dddd01d3f86fd968e32d204ba7e6e6d8f47
Resetting panda
deviceState: Reader was evicted, reconnecting
deviceState: Reader was evicted, reconnecting
ui deleter logmessaged pandad thermald
reconnecting is taking 1 seconds...
ui deleter logmessaged pandad thermald
{"event": "STATUS_PACKET", "count": 0, "pandaState": null, "location": null, "deviceState": {"deviceState": {"freeSpacePercent": 40.760162353515625, "batteryPercent": 100, "batteryStatus": "Charging", "fanSpeedPercentDesired": 0, "started": false, "usbOnline": false, "startedMonoTime": 0, "thermalStatus": "green", "batteryCurrent": 0, "batteryVoltage": 0, "chargingError": false, "chargingDisabled": false, "memoryUsagePercent": 21, "cpuUsagePercent": 6, "networkType": "wifi", "offroadPowerUsageUwh": 0, "networkStrength": "unknown", "carBatteryCapacityUwh": 3000000, "cpuTempC": [0.0], "gpuTempC": [0.0], "memoryTempC": 0.0, "batteryTempC": 0.0, "ambientTempC": 0.0, "lastAthenaPingTime": 0, "gpuUsagePercent": 0}, "logMonoTime": 3925929640799, "valid": true}}
reconnecting is taking 2 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 3 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 4 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 5 seconds...
ui deleter logmessaged pandad thermald
reconnecting is taking 6 seconds...
ui deleter logmessaged pandad thermald
reconnecting is taking 7 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 8 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 9 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 10 seconds...
ui deleter logmessaged pandad thermald
reconnecting is taking 11 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 12 seconds...
ui deleter logmessaged pandad thermald
reconnecting is taking 13 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 14 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
reconnecting is taking 15 seconds...
ui deleter logmessaged pandad thermald
ui deleter logmessaged pandad thermald
crash
Traceback (most recent call last):
  File "/openpilot/selfdrive/manager/process.py", line 36, in launcher
    mod.main()
  File "/openpilot/selfdrive/pandad.py", line 94, in main
    panda.reset()
  File "/openpilot/panda/python/__init__.py", line 218, in reset
    self.reconnect()
  File "/openpilot/panda/python/__init__.py", line 239, in reconnect
    raise Exception("reconnect failed")
Exception: reconnect failed
Process pandad:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/openpilot/selfdrive/manager/process.py", line 36, in launcher
    mod.main()
  File "/openpilot/selfdrive/pandad.py", line 94, in main
    panda.reset()
  File "/openpilot/panda/python/__init__.py", line 218, in reset
    self.reconnect()
  File "/openpilot/panda/python/__init__.py", line 239, in reconnect
    raise Exception("reconnect failed")
Exception: reconnect failed
...
```

Operating system: Host Ubuntu 18.04,  ghcr.io/commaai/openpilot-sim Ubuntu 20.04

**Comment by Torch-HXM** [comment]
Hello!May I konw your solution?I have the same problem.
