### ISSUE TITLE
Carla camera data not showing in openpilot UI. Openpilot not working with Carla

### ISSUE THREAD

**Issue by pgchui** [commaai/openpilot#22465]
**Describe the bug**
openpilot did not work with carla. openpilot UI did not show camera data. Client in carla did not move at all.

**How to reproduce or log data**
Console output:
```
Killing old publisher: roadCameraState
Traceback (most recent call last):
  File "./bridge.py", line 69, in cam_callback
    pm.send('roadCameraState', dat)
  File "/openpilot/cereal/messaging/__init__.py", line 248, in send
    self.sock[s].send(dat)
  File "cereal/messaging/messaging_pyx.pyx", line 149, in cereal.messaging.messaging_pyx.PubSocket.send
cereal.messaging.messaging_pyx.MultiplePublishersError
```
1. follow steps in [setup](https://github.com/commaai/openpilot/wiki/Requirements)
2. `./start_carla.sh`
3. `./start_openpilot_docker.sh`

**Additional context**

Operating system: Ubuntu 20.04
NVIDIA-SMI: 470.63.01
CUDA Version: 11.4

**Comment by pgchui** [comment]
Adding `USE_FRAME_STREAM=1` fixed the camera feed issue but new issue arose. After press 1, in console output of bridge.py, engaged changed from false to true. Right before the engaged value change, console printed:
carControl: Reader was evicted, reconnecting
controlsState: Reader was evicted, reconnecting
And openpilot UI showed "openpilot unavailable. Communication issue between processes."
