### ISSUE TITLE
LogReader unable to read some rlog.bz2 files.

### ISSUE THREAD

**Issue by uyrusali** [commaai/openpilot#23188]
### Describe the bug

[rlog.zip](https://github.com/commaai/openpilot/files/7691221/rlog.zip)

``` python
#%%
import os
import pandas as pd
# from tools.lib.logreader import LogReader
from tools.lib.robust_logreader import RobustLogReader
from datetime import datetime
import glob
import pytz
from pathlib import Path
import tools.lib.logreader
files=[]

files.append('rlog.bz2')

for file in files:
    print(file)
    lr=RobustLogReader(file)
    logs=list(lr)
    print([set(l.which() for l in logs)])

```
Unable to read attached rlog file using the script above. I was able to read other rlog files, and qlog files from this trip using the same script, but reading rlog files from this trip gives the following error. Tried both LogReader and RobustLogReader. PlotJuggler opens the same files with no problem.

```
Traceback (most recent call last):
  File "capnp/lib/capnp.pyx", line 1165, in capnp.lib.capnp._DynamicStructReader._which
RuntimeError: Member was null.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/IMU/micgihan_converter.py", line 32, in <module>
    print([set(l.which() for l in logs)])
  File "/home/ubuntu/PycharmProjects/IMU/micgihan_converter.py", line 32, in <genexpr>
    print([set(l.which() for l in logs)])
  File "capnp/lib/capnp.pyx", line 1182, in capnp.lib.capnp._DynamicStructReader.which.__get__
  File "capnp/lib/capnp.pyx", line 1168, in capnp.lib.capnp._DynamicStructReader._which
capnp.lib.capnp.KjException: Attempted to call which on a non-union type
```

### OS Version

Ubuntu 20.04

**Comment by pd0wm** [comment]
Is your `cereal` repo (specifically log.capnp), on the same version as was used to generate the logs?

**Comment by uyrusali** [comment]
That's true, it was my mistake. The problem was using the older cereal repo in a virtual environment.

Problem solved with using the most recent cereal version.

Thank you @pd0wm !
