### ISSUE TITLE
pip dependencies failing on Ubuntu 21.10: missing libffi.so.7

### ISSUE THREAD

**Issue by JasonJShuler** [commaai/openpilot#23572]
### Describe the bug

tools/ubuntu_setup.sh and update_requirements.sh fails on Ubuntu 21.10 while installing the package "control" with the error "ImportError: libffi.so.7: cannot open shared object file: No such file or directory". Full error message at end.

Quick search indicates libffi.so.7 is included in Ubuntu 20.04, but was removed from 21.10. This issue was not present a few days ago - unsure what changed.

UPDATE: I found a workaround, but this doesn't explain what changed...

`wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
sudo dpkg -i libffi7_3.3-4_amd64.deb`

Full output:

`An error occurred while installing control==0.9.1 --hash=sha256:8c9084bf386eafcf5d74008f780fae6dec68d243d18a380c866ac10a3549f8d3! Will try again.
An error occurred while installing sphinx-sitemap==2.2.0 --hash=sha256:65adda39233cb17c0da10ba1cebaa2df73e271cdb6f8efd5cec8eef3b3cf7737! Will try again.
An error occurred while installing pytools==2021.2.9; python_version ~= '3.6' --hash=sha256:db6cf83c9ba0a165d545029e2301621486d1e9ef295684072e5cd75316a13755! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting control==0.9.1
[pipenv.exceptions.InstallError]:   Using cached control-0.9.1.tar.gz (357 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /home/user/.local/share/virtualenvs/openpilot-LdCniAIp/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-detr8g4w/control_c1fda77285224b28b7bd1fbe995094a2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-detr8g4w/control_c1fda77285224b28b7bd1fbe995094a2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_44g3q5m
[pipenv.exceptions.InstallError]:        cwd: /tmp/pip-install-detr8g4w/control_c1fda77285224b28b7bd1fbe995094a2/
[pipenv.exceptions.InstallError]:   Complete output (13 lines):
[pipenv.exceptions.InstallError]:   Traceback (most recent call last):
[pipenv.exceptions.InstallError]:     File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:     File "/home/user/.local/share/virtualenvs/openpilot-LdCniAIp/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
[pipenv.exceptions.InstallError]:       from setuptools.dist import Distribution
[pipenv.exceptions.InstallError]:     File "/home/user/.local/share/virtualenvs/openpilot-LdCniAIp/lib/python3.8/site-packages/_virtualenv.py", line 89, in exec_module
[pipenv.exceptions.InstallError]:       old(module)
[pipenv.exceptions.InstallError]:     File "/home/user/.local/share/virtualenvs/openpilot-LdCniAIp/lib/python3.8/site-packages/setuptools/dist.py", line 37, in <module>
[pipenv.exceptions.InstallError]:       from setuptools import windows_support
[pipenv.exceptions.InstallError]:     File "/home/user/.local/share/virtualenvs/openpilot-LdCniAIp/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
[pipenv.exceptions.InstallError]:       import ctypes
[pipenv.exceptions.InstallError]:     File "/home/user/.pyenv/versions/3.8.10/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[pipenv.exceptions.InstallError]:       from _ctypes import Union, Structure, Array
[pipenv.exceptions.InstallError]:   ImportError: libffi.so.7: cannot open shared object file: No such file or directory
[pipenv.exceptions.InstallError]:   ----------------------------------------
[pipenv.exceptions.InstallError]: WARNING: Discarding https://files.pythonhosted.org/packages/25/52/17664c8ff44acd09ec8097329b6e4302a6c44bbb52c67e61cf85450567df/control-0.9.1.tar.gz#sha256=8c9084bf386eafcf5d74008f780fae6dec68d243d18a380c866ac10a3549f8d3 (from https://pypi.org/simple/control/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement control==0.9.1 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.5, 0.6.6, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for control==0.9.1
ERROR: Couldn't install package: control
`

### OS Version

Ubuntu 21.10

### openpilot version or commit

d31ff2cf496563f2ed4d8bc5ca45d06bb6df7831

### Additional info

Just merged master - it had been working fine.

**Comment by JasonJShuler** [comment]
I tried removing the pipenv and it made things worse; still crashing on the same dependency though...

**Comment by JasonJShuler** [comment]
Based on this https://askubuntu.com/a/1300763/1519047

I ran the following commands and the issue was resolved... but I'm still unclear about what changed.

`wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
sudo dpkg -i libffi7_3.3-4_amd64.deb`

**Comment by JasonJShuler** [comment]
Could not reproduce on clean install of Ubuntu 21.10 - assuming my install has become corrupt. Closing.
