### ISSUE TITLE
PC: Fix modeld crash when using CAN replay

### ISSUE THREAD

**Issue by sshane** [commaai/openpilot#23695]
### Describe the bug

When using CAN replay on PC with jungle and panda, modeld crashes with:

```
Traceback (most recent call last):
  File "/home/batman/openpilot/selfdrive/modeld/runners/onnx_runner.py", line 60, in <module>
    run_loop(ort_session)
  File "/home/batman/openpilot/selfdrive/modeld/runners/onnx_runner.py", line 34, in run_loop
    inputs.append(read(ts).reshape(shp))
  File "/home/batman/openpilot/selfdrive/modeld/runners/onnx_runner.py", line 17, in read
    assert(len(st) > 0)
AssertionError
```

**Comment by adeebshihadeh** [comment]
probably a duplicate of  #23666

**Comment by maykonpacheco** [comment]
that's right
