### ISSUE TITLE
Carla bridge.py raising MultiplePublishersError

### ISSUE THREAD

**Issue by Ruishenl** [commaai/openpilot#26808]
### Describe the bug

The following exception logs keeps showing when following the guideline running the carla integration with openpilot:

```Killing old publisher: wideRoadCameraState                                                                                                                  
Traceback (most recent call last):                                                                                                                          
  File "./bridge.py", line 97, in cam_callback_wide_road                                                                                                    
    self._cam_callback(image, self.frame_wide_id, 'wideRoadCameraState', VisionStreamType.VISION_STREAM_WIDE_ROAD)                                          
  File "./bridge.py", line 123, in _cam_callback                                                                                                            
    pm.send(pub_type, dat)                                                                                                                                  
  File "/openpilot/cereal/messaging/__init__.py", line 259, in send                                                                                         
    self.sock[s].send(dat)                                                                                                                                  
  File "cereal/messaging/messaging_pyx.pyx", line 149, in cereal.messaging.messaging_pyx.PubSocket.send                                                     
cereal.messaging.messaging_pyx.MultiplePublishersError                                                                                                      
Killing old publisher: gpsLocationExternal                                                                                                                  
Traceback (most recent call last):                                                                                                                          
  File "./bridge.py", line 368, in <lambda>                                                                                                                 
Killing old publisher: accelerometer                                                                                                                        
Traceback (most recent call last):                                                                                                                          
  File "./bridge.py", line 364, in <lambda>                                                                                                                 
    imu.listen(lambda imu: imu_callback(imu, vehicle_state))                                                                                                
  File "./bridge.py", line 135, in imu_callback                                                                                                             
    gps.listen(lambda gps: gps_callback(gps, vehicle_state))                                                                                                
  File "./bridge.py", line 206, in gps_callback                                                                                                             
    pm.send('accelerometer', dat)                                                                                                                           
  File "/openpilot/cereal/messaging/__init__.py", line 259, in send                                                                                         
    self.sock[s].send(dat)                                                                                                                                  
  File "cereal/messaging/messaging_pyx.pyx", line 149, in cereal.messaging.messaging_pyx.PubSocket.send                                                     
    pm.send('gpsLocationExternal', dat)                                                                                                                     
  File "/openpilot/cereal/messaging/__init__.py", line 259, in send                                                                                         
    cereal.messaging.messaging_pyxself.sock[s].send(dat)                                                                                                    
.MultiplePublishersError  File "cereal/messaging/messaging_pyx.pyx", line 149, in cereal.messaging.messaging_pyx.PubSocket.send          
```

I am running on master branch and simply following the [instruction](https://github.com/commaai/openpilot/blob/master/tools/sim/README.md) here.

### OS Version

Pop!_OS 22.04

### openpilot version or commit

 2ac87a0a456ee4a2ffc66986c86e5c7e5d44f930

**Comment by jon-chuang** [comment]
`MultiplePublishersError` results from `errno.EADDRINUSE`

One explanation is that you have 2 installs of openpilot on your system, both are running at the same time. Both `Pub/SubMaster`s will try to create UDP (msgq - IPC) or TCP sockets (zmq) with the same address, which may return `EADDRINUSE`...
