### ISSUE TITLE
tici: DBus service unknown

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#29172]
```
Error getting hardware state
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/thermald/thermald.py", line 140, in hw_state_thread
    network_info=HARDWARE.get_network_info(),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/system/hardware/tici/hardware.py", line 209, in get_network_info
    modem = self.get_modem()
            ^^^^^^^^^^^^^^^^
  File "/data/openpilot/system/hardware/tici/hardware.py", line 165, in get_modem
    objects = self.mm.GetManagedObjects(dbus_interface="org.freedesktop.DBus.ObjectManager", timeout=TIMEOUT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.6 was not provided by any .service files
```

**Comment by jnewb1** [comment]
example route: 'a752a19628873b10|2023-07-30--11-43-45'
