### ISSUE TITLE
Replay UI: ValueError: zip() argument 2 is longer than argument 1

### ISSUE THREAD

**Issue by rmcc22** [commaai/openpilot#29383]
### Describe the bug

```
(openpilot-py3.11) root@MSI:~/openpilot# python tools/replay/ui.py
pygame 2.5.0 (SDL 2.28.0, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/root/openpilot/tools/replay/ui.py", line 228, in <module>
    ui_thread(args.ip_address)
  File "/root/openpilot/tools/replay/ui.py", line 100, in ui_thread
    draw_plots = init_plots(plot_arr, name_to_arr_idx, plot_xlims, plot_ylims, plot_names, plot_colors, plot_styles)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/openpilot/tools/replay/lib/ui_helpers.py", line 163, in init_plots
    axs[i].set_title(", ".join(f"{nm} ({cl})"
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/openpilot/tools/replay/lib/ui_helpers.py", line 163, in <genexpr>
    axs[i].set_title(", ".join(f"{nm} ({cl})"
                              ^^^^^^^^^^^^^^^
ValueError: zip() argument 2 is longer than argument 1
(openpilot-py3.11) root@MSI:~/openpilot#
```

### OS Version

WSL2 python

**Comment by jnewb1** [comment]
https://github.com/commaai/openpilot/blob/0bacd9882875b4b0c3ad206dbc365ccae5464564/tools/replay/lib/ui_helpers.py#L164

introduced in: https://github.com/commaai/openpilot/pull/29336
