### ISSUE TITLE
master branch build error

### ISSUE THREAD

**Issue by crwusiz** [commaai/openpilot#30006]
### Describe the bug

python3 cereal/services.py > cereal/services.h
Traceback (most recent call last):
  File "cereal/services.py", line 21, in <module>
    services: dict[str, tuple] = {
TypeError: 'type' object is not subscriptable
scons: *** [cereal/services.h] Error 1
scons: building terminated because of errors.
scons build failed
Traceback (most recent call last):
  File "cereal/services.py", line 21, in <module>
    services: dict[str, tuple] = {
TypeError: 'type' object is not subscriptable
scons: *** [cereal/services.h] Error 1

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

### OS Version

ubuntu 20.04

**Comment by crwusiz** [comment]
last commit : 362c0bf2cadc3b54ad62472755a507fd6b3af825

**Comment by crwusiz** [comment]
(https://github.com/commaai/openpilot/blob/master/tools/install_python_dependencies.sh)

build no error ^^;
