### ISSUE TITLE
rawgpsd crash 

### ISSUE THREAD

**Issue by devtekve** [commaai/openpilot#30226]
### Describe the bug

Sometimes from time to time `rawgpsd` crashes out of the blue. I see this stack trace tho: 

```
Traceback (most recent call last):
  File "/data/openpilot/openpilot/selfdrive/manager/process.py", line 40, in launcher
    mod.main()
  File "/data/openpilot/system/sensord/rawgps/rawgpsd.py", line 288, in main
    r = setup_quectel(diag)
        ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/system/sensord/rawgps/rawgpsd.py", line 223, in setup_quectel
    send_recv(diag, DIAG_SUBSYS_CMD_F, pack('<BHBBIIII',
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 65, in send_recv
    opcode, payload = diag.recv()
                      ^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 48, in recv
    unframed_message = self.hdlc_decapsulate(raw_payload)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/sensord/rawgps/modemdiag.py", line 35, in hdlc_decapsulate
    assert payload[-2:] == pack('<H', ModemDiag.ccitt_crc16(payload[:-2]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
``` 

### Provide a route where the issue occurs

e1107f9d04dfb1e2|2023-10-12--16-42-26--0

### openpilot version

0.9.5

### Additional info

I have observed this on master stock, but this route was captured in sunnypilot tho

**Comment by devtekve** [comment]
Oh, I had reported a similar incident but with stock openpilot too! here's that issue report https://github.com/commaai/openpilot/issues/30226
