### ISSUE TITLE
micd crash in CI

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/openpilot#30634]
https://jenkins.comma.life/blue/organizations/jenkins/openpilot/detail/setup-retry/2/pipeline

```
crash

Traceback (most recent call last):

  File "/data/pythonpath/openpilot/selfdrive/manager/process.py", line 40, in launcher

    mod.main()

  File "/data/pythonpath/system/micd.py", line 92, in main

    mic.micd_thread()

  File "/data/pythonpath/system/micd.py", line 84, in micd_thread

    with sd.InputStream(channels=1, samplerate=SAMPLE_RATE, callback=self.callback) as stream:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/sounddevice.py", line 1421, in __init__

    _StreamBase.__init__(self, kind='input', wrap_callback='array',

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/sounddevice.py", line 898, in __init__

    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/sounddevice.py", line 2745, in _check

    raise PortAudioError(errormsg, err, hosterror_info)

sounddevice.PortAudioError: Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'Operation already in progress' [ALSA error -114]
```

**Comment by adeebshihadeh** [comment]
@jnewb1 is this fixed?
