### ISSUE TITLE
manager.py fails to start after upgrading to agnos 9, 

### ISSUE THREAD

**Issue by deanlee** [commaai/openpilot#30643]
### Describe the bug

Manager failed to start
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/manager/./manager.py", line 231, in <module>
    main()
  File "/data/openpilot/selfdrive/manager/./manager.py", line 199, in main
    manager_prepare()
  File "/data/openpilot/selfdrive/manager/./manager.py", line 113, in manager_prepare
    p.prepare()
  File "/data/openpilot/openpilot/selfdrive/manager/process.py", line 213, in prepare
    importlib.import_module(self.module)
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/openpilot/system/webrtc/webrtcd.py", line 21, in <module>
    from teleoprtc import WebRTCAnswerBuilder
ModuleNotFoundError: No module named 'teleoprtc'

### Provide a route where the issue occurs

no

### openpilot version

0.8.10

**Comment by deanlee** [comment]
OIC
