### ISSUE TITLE
remaining jenkins issues

### ISSUE THREAD

**Issue by jnewb1** [commaai/openpilot#31415]
occasionally mapsd will fail the timing check, looks like it has 1 frame (or perhaps several) where is takes over 2 seconds to render. Perhaps related to maplibre change? We use the second segment for these calculations so I don't think it's just the first frame that has this issue

heres one instance, seen this several times
https://jenkins.comma.life/blue/organizations/jenkins/openpilot/detail/master/1/pipeline

```
Not equal to tolerance rtol=0.03, atol=0

navModel - failed mean timing check

Mismatched elements: 1 / 1 (100%)

Max absolute difference: 0.01853632

Max relative difference: 0.03707265

 x: array(0.518536)

 y: array(0.5)

navModel - failed RSD timing check

navModel                                : [ 518.53632262 2653.572946    477.996837  ]

                                          5.307145892 0.39999371523278215


Not equal to tolerance rtol=0.03, atol=0

mapRenderState - failed mean timing check

Mismatched elements: 1 / 1 (100%)

Max absolute difference: 0.01846009

Max relative difference: 0.03692019

 x: array(0.51846)

 y: array(0.5)

mapRenderState - failed RSD timing check

mapRenderState                          : [ 518.4600927 2653.586175   468.035681 ]

                                          5.30717235 0.40006562129274587

```

tizi qcomgps test failures:

```
error: couldn't find modem

at_cmd failed, trying again

Traceback (most recent call last):

  File "/data/openpilot/openpilot/common/retry.py", line 13, in wrapper

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/data/openpilot/openpilot/system/qcomgpsd/qcomgpsd.py", line 94, in at_cmd

    return subprocess.check_output(f"mmcli -m any --timeout 30 --command='{cmd}'", shell=True, encoding='utf8')

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 466, in check_output

    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command 'mmcli -m any --timeout 30 --command='AT+QGPSDEL=0'' returned non-zero exit status 1.

error: couldn't find modem

at_cmd failed, trying again

Traceback (most recent call last):

  File "/data/openpilot/openpilot/common/retry.py", line 13, in wrapper

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/data/openpilot/openpilot/system/qcomgpsd/qcomgpsd.py", line 94, in at_cmd

    return subprocess.check_output(f"mmcli -m any --timeout 30 --command='{cmd}'", shell=True, encoding='utf8')

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 466, in check_output

    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command 'mmcli -m any --timeout 30 --command='AT+QGPSDEL=0'' returned non-zero exit status 1.

error: couldn't find modem

at_cmd failed, trying again

Traceback (most recent call last):

  File "/data/openpilot/openpilot/common/retry.py", line 13, in wrapper

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/data/openpilot/openpilot/system/qcomgpsd/qcomgpsd.py", line 94, in at_cmd

    return subprocess.check_output(f"mmcli -m any --timeout 30 --command='{cmd}'", shell=True, encoding='utf8')

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 466, in check_output

    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run

    raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command 'mmcli -m any --timeout 30 --command='AT+QGPSDEL=0'' returned non-zero exit status 1.

```

tizi amp failures:
```
elf = <system.hardware.tici.tests.test_amplifier.TestAmplifier testMethod=test_init_while_siren_play>


    def test_init_while_siren_play(self):

      for _ in range(10):

        self.panda.set_siren(False)

        time.sleep(0.1)

    

        self.panda.set_siren(True)

        time.sleep(random.randint(0, 5))

    

        amp = Amplifier(debug=True)

        r = amp.initialize_configuration(Tici().get_device_type())

>       assert r

E       assert False


system/hardware/tici/tests/test_amplifier.py:66: AssertionError

---------------------------- Captured stdout setup -----------------------------

No IRQs found for 'xhci-hcd:usb3'

----------------------------- Captured stdout call -----------------------------

Setting "Global shutdown" to 0:

  Changed 0x51: 0x81 -> 0x1

Setting "MCLK prescaler" to 1:

  Changed 0x10: 0x10 -> 0x10

Setting "PM: enable speakers" to 3:

  Changed 0x4d: 0x73 -> 0x73

Setting "PM: enable DACs" to 3:

  Changed 0x4d: 0x73 -> 0x73

Setting "Enable PLL1" to 1:

  Changed 0x12: 0x80 -> 0x80

Setting "Enable PLL2" to 1:

  Changed 0x1a: 0x80 -> 0x80

Setting "DAI1: I2S mode" to 4:

  Changed 0x14: 0x10 -> 0x10

Setting "DAI2: I2S mode" to 4:

  Changed 0x1c: 0x10 -> 0x10

Setting "DAI1 Passband filtering: music mode" to 1:

  Changed 0x18: 0x80 -> 0x80

Setting "DAI1 voice mode gain (DV1G)" to 0:

  Changed 0x2f: 0x0 -> 0x0

Setting "DAI1 attenuation (DV1)" to 0:

  Changed 0x2f: 0x0 -> 0x0

Setting "DAI2 attenuation (DV2)" to 0:

  Changed 0x31: 0x0 -> 0x0

Setting "DAI2: DC blocking" to 1:

  Changed 0x20: 0x0 -> 0x1

Setting "DAI2: High sample rate" to 0:

  Changed 0x20: 0x1 -> 0x1

Setting "ALC enable" to 1:

  Changed 0x43: 0x58 -> 0xd8

Setting "ALC/excursion limiter release time" to 5:

  Changed 0x43: 0xd8 -> 0xd8

Setting "ALC multiband enable" to 1:

  Changed 0x43: 0xd8 -> 0xd8

Setting "DAI1 EQ enable" to 0:

  Changed 0x49: 0x40 -> 0x40

Setting "DAI2 EQ clip detection disabled" to 1:

  Changed 0x32: 0x12 -> 0x12

Setting "DAI2 EQ attenuation" to 5:

  Changed 0x32: 0x12 -> 0x15

Setting "Excursion limiter upper corner freq" to 4:

  Changed 0x41: 0x10 -> 0x40

Setting "Excursion limiter lower corner freq" to 0:

  Changed 0x41: 0x40 -> 0x40

Setting "Excursion limiter threshold" to 0:

  Changed 0x42: 0x4 -> 0x0

Setting "Distortion limit (THDCLP)" to 6:

  Changed 0x46: 0x1 -> 0x61

Setting "Distortion limiter release time constant" to 0:

  Changed 0x46: 0x61 -> 0x60

Setting "Right DAC input mixer: DAI1 left" to 0:

  Changed 0x22: 0x21 -> 0x21

Setting "Right DAC input mixer: DAI1 right" to 0:

  Changed 0x22: 0x21 -> 0x21

Setting "Right DAC input mixer: DAI2 left" to 1:

  Changed 0x22: 0x21 -> 0x23

Setting "Right DAC input mixer: DAI2 right" to 0:

  Changed 0x22: 0x23 -> 0x22

Setting "DAI1 audio port selector" to 2:

  Changed 0x16: 0x83 -> 0x83

Setting "DAI2 audio port selector" to 1:

  Changed 0x1e: 0x43 -> 0x43

Setting "Enable left digital microphone" to 1:

  Changed 0x48: 0x30 -> 0x30

Setting "Enable right digital microphone" to 1:

  Changed 0x48: 0x30 -> 0x30

Setting "Enhanced volume smoothing disabled" to 0:

  Changed 0x49: 0x40 -> 0x40

Setting "Volume adjustment smoothing disabled" to 0:

  Changed 0x49: 0x40 -> 0x0

Setting "Zero-crossing detection disabled" to 0:

  Changed 0x49: 0x0 -> 0x0

Setting "Left speaker output from left DAC" to 1:

  Changed 0x2b: 0x3 -> 0x1

Setting "Right speaker output from right DAC" to 1:

  Changed 0x2c: 0x3 -> 0x1

Setting "Left Speaker Mixer Gain" to 0:

  Changed 0x2d: 0x0 -> 0x0

Setting "Right Speaker Mixer Gain" to 0:

  Changed 0x2d: 0x0 -> 0x0

Setting "Left speaker output volume" to 23:

  Changed 0x3d: 0x17 -> 0x17

Setting "Right speaker output volume" to 23:

  Changed 0x3e: 0x17 -> 0x17

Setting "DAI2 EQ enable" to 0:

  Changed 0x49: 0x0 -> 0x0

Setting "DAI2: DC blocking" to 0:

  Changed 0x20: 0x1 -> 0x0

Setting "ALC enable" to 0:

  Changed 0x43: 0xd8 -> 0x58

Setting "DAI2 EQ attenuation" to 2:

  Changed 0x32: 0x15 -> 0x12

Setting "Excursion limiter upper corner freq" to 1:

  Changed 0x41: 0x40 -> 0x10

Setting "Excursion limiter threshold" to 4:

  Changed 0x42: 0x0 -> 0x4

Setting "Distortion limit (THDCLP)" to 0:

  Changed 0x46: 0x60 -> 0x0

Setting "Distortion limiter release time constant" to 1:

  Changed 0x46: 0x0 -> 0x1

Setting "Left DAC input mixer: DAI1 left" to 0:

Failed to set amp config, 14 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 13 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 12 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 11 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 10 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 9 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 8 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 7 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 6 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 5 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 4 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 3 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 2 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 1 retries left

Setting "Global shutdown" to 0:

Failed to set amp config, 0 retries left

```

boardd didn't stop in test_board_loopback

![image](https://github.com/commaai/openpilot/assets/9648890/ee8956ff-9626-4433-93ba-7be9e66a1fd8)

**Comment by adeebshihadeh** [comment]
Any logs indicating what was going on? https://github.com/commaai/openpilot/issues/31333 should help with this

https://github.com/commaai/openpilot/blob/22c966d8fd20d94a883d80cdd5b7830e1fd35b84/selfdrive/navd/map_renderer.cc#L117C27-L124C17
