### ISSUE TITLE
MetaDrive :ShowBase(warning): Unable to open 'offscreen' window.

### ISSUE THREAD

**Issue by dennisklad** [commaai/openpilot#31797]
### Describe the bug

Hi,

I am running OP on PC and MetaDrive was working fine yesterday, but when I started the bridge today I received following error. 
After looking around for multiple hours, reinstalling the poetry env, etc. I was not able to resolve this issue. I am rather unsure if this issue is caused by OP, by MetaDrive or by some Ubuntu drivers, but would really appreciate if anybody know how to fix it.

Thanks in advance.

```
----------------------------------------------------------
---- Spawning Metadrive world, this might take awhile ----
----------------------------------------------------------
[INFO] Environment: MetaDriveEnv
[INFO] MetaDrive version: 0.4.2.2
[INFO] Sensors: [lidar: Lidar(), side_detector: SideDetector(), lane_line_detector: LaneLineDetector(), rgb_road: RGBCameraRoad(1928, 1208)]
[INFO] Render Mode: offscreen
[INFO] Horizon (Max steps per agent): None
[INFO] Assets version: 0.4.2.2
:ShowBase(warning): Unable to open 'offscreen' window.
Process metadrive process:
Traceback (most recent call last):
  File "/home/n/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/n/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/n/Masterarbeit/openpilot-plugin/openpilot/tools/sim/bridge/metadrive/metadrive_process.py", line 63, in metadrive_process
    reset()
  File "/home/n/Masterarbeit/openpilot-plugin/openpilot/tools/sim/bridge/metadrive/metadrive_process.py", line 60, in reset
    env.reset()
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/metadrive/envs/base_env.py", line 513, in reset
    self.lazy_init()  # it only works the first time when reset() is called to avoid the error when render
    ^^^^^^^^^^^^^^^^
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/metadrive/envs/base_env.py", line 406, in lazy_init
    initialize_engine(self.config)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/metadrive/engine/engine_utils.py", line 12, in initialize_engine
    cls.singleton = cls(env_global_config)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/metadrive/engine/base_engine.py", line 55, in __init__
    EngineCore.__init__(self, global_config)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/metadrive/engine/core/engine_core.py", line 190, in __init__
    super(EngineCore, self).__init__(windowType=self.mode)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 341, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 1026, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 1061, in openMainWindow
    self.openWindow(*args, **kw)
  File "/home/n/Masterarbeit/openpilot-plugin/.venv/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 806, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.
```

### OS Version

Ubuntu 20.04

**Comment by yang-ze-kang** [comment]
I meet the same problem. Have you soloved it?
