### ISSUE TITLE
juggle.py: timeless routes not supported

### ISSUE THREAD

**Issue by BBBmau** [commaai/openpilot#32117]
### Describe the bug

When providing a timeless route, we get a panic. This comes from timeless routes being introduced from this PR https://github.com/commaai/openpilot/pull/31119

```py
(openpilot-py3.11) ➜  plotjuggler git:(master) ✗ ./juggle.py "4203853bc02e087a/0000004e--2f809c6660/0"
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1002)'))': /4203853bc02e087a/None/0/rlog.bz2
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1002)'))': /4203853bc02e087a/None/0/rlog.bz2
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1002)'))': /4203853bc02e087a/None/0/rlog.bz2
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1002)'))': /4203853bc02e087a/None/0/rlog.bz2
Traceback (most recent call last):
  File "/home/mau/Dev/openpilot/tools/plotjuggler/./juggle.py", line 133, in <module>
    juggle_route(route_or_segment_name, args.can, args.layout, args.dbc)
  File "/home/mau/Dev/openpilot/tools/plotjuggler/./juggle.py", line 79, in juggle_route
    sr = LogReader(route_or_segment_name, default_mode=ReadMode.AUTO_INTERACTIVE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mau/Dev/openpilot/openpilot/tools/lib/logreader.py", line 256, in __init__
    self.reset()
  File "/home/mau/Dev/openpilot/openpilot/tools/lib/logreader.py", line 279, in reset
    self.logreader_identifiers = self._parse_identifiers(self.identifier)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mau/Dev/openpilot/openpilot/tools/lib/logreader.py", line 239, in _parse_identifiers
    identifiers = source(sr, mode)
                  ^^^^^^^^^^^^^^^^
  File "/home/mau/Dev/openpilot/openpilot/tools/lib/logreader.py", line 191, in auto_source
    raise Exception(f"auto_source could not find any valid source, exceptions for sources: {exceptions}")
Exception: auto_source could not find any valid source, exceptions for sources: [MaxRetryError("HTTPSConnectionPool(host='data-raw.comma.internal', port=443): Max retries exceeded with url: /4203853bc02e087a/None/0/rlog.bz2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1002)')))"), AssertionError(), UnauthorizedError('Unauthorized. Authenticate with tools/lib/auth.py'), AssertionError()]
```

- [ ] Update docs to have timeless routes
- [ ] Should still support both route id versions (maybe?)

### OS Version

Ubuntu 20.04

### openpilot version or commit

c95404d564a9a8d168f8f587887e9c33f96db861

**Comment by adeebshihadeh** [comment]
The new format is supported. Your route is likely just missing rlogs being uploaded. Add "/q" at the end if you want the qlogs.
