### ISSUE TITLE
UI doesn't show camera feed for CTF replay route

### ISSUE THREAD

**Issue by Quantizr** [commaai/openpilot#32778]
### Describe the bug

For the route in [CTF](https://github.com/commaai/openpilot/blob/master/tools/CTF.md):
```bash
# start the route reply
cd tools/replay
./replay '0c7f0c7f0c7f0c7f|2021-10-13--13-00-00' --dcam --ecam

# start the UI in another terminal
selfdrive/ui/ui
```

The UI does not switch to the onroad display. The UI is receiving data as the camera feed can be viewed in Settings -> Device -> Driver Camera, the issue is probably with the format of the CTF route itself.

Starting the demo replay (`/replay --demo --dcam --ecam`), stopping the demo, then starting the CTF replay allows the CTF replay to work.

### OS Version

Ubuntu 20.04

**Comment by sshane** [comment]
This is an old route that uses the deprecated `pandaState` service for ignition, @adeebshihadeh should we deprecate the CTF or support the old service in UI?

**Comment by adeebshihadeh** [comment]
I'd prefer regenerating the route. I think it should be easy: `xx/projects/ctf`.

**Comment by bravochar** [comment]
I am running into this issue as well. I can also verify that the driver camera preview will work, but my UI does not switch to the onroad display, even after pausing/resuming the replay or even quitting and reloading the replay.

**Comment by MikeBusuttil** [comment]
yo @adeebshihadeh wanna pair on this? 😄

**Comment by royjr** [comment]
same here, demo route works fine though

**Comment by jyoung8607** [comment]
For benefit of others looking at this issue, Shane and Adeeb already triaged it above, and they're going to fix it by regenerating the CTF route itself. The old CTF route has the ignition-on state in a place we no longer look for it.

**Comment by robbiewu008** [comment]
Same issue with MacOS 15.3.1, Any update?

**Comment by Sanaznor71** [comment]
Having same problem!
Would be great if you have any update.
Thanks

**Comment by PrabodhGyawali** [comment]
I assume we can checkout to 3 years ago when it worked do you know which commit hash to checkout to?

**Comment by MikeBusuttil** [comment]
Nah its not the code, its the route that's stored on comma's server.  Nag @sshane or @adeebshihadeh and they'll be able to regenerate that route and fix it.  I hope they do

**Comment by ealderman-25** [comment]
Ran into this today.
In the meantime, you can instead run `selfdrive/debug/uiview.py` as a workaround.

**Comment by HeathNaylor** [comment]
Right now does this block CTF participation? I am just getting started learning openpilot and [this blog post](https://blog.comma.ai/welcome-to-the-openpilot-team/) recommends starting with the CTF that is having issues.

**Comment by MikeBusuttil** [comment]
nah you can still do the CTF it just makes it a little trickier to get started

**Comment by speedyconzales** [comment]
would love to see this updated, since it is in this state for over a year.

**Comment by thenewwazoo** [comment]
I also stubbed my toe on this and decided to give up on the CTF. The [turn the speed blue](https://docs.comma.ai/how-to/turn-the-speed-blue/) guide did work.

**Comment by itishermann** [comment]
Hitting this on macOS (Apple Silicon, openpilot master @ fcb0a496e) following the exact reproduction steps from `tools/CTF.md`. Worth flagging that with the current Python+raylib UI, the symptom has regressed from "doesn't switch to onroad" into two hard crashes before reaching that state.

### Environment
- macOS 15 (Apple Silicon)
- Python 3.12.13, uv 0.11.x
- openpilot master, commit `fcb0a496e`
- Replay 0.11.1, route `0c7f0c7f0c7f0c7f|2021-10-13--13-00-00 --dcam --ecam`

### Crash 1 — onboarding face detection (only on fresh setup, before terms accepted)

```
Traceback (most recent call last):
  File "selfdrive/ui/ui.py", line 36, in <module>
    main()
  ...
  File "selfdrive/ui/mici/onroad/driver_camera_dialog.py", line 163, in _draw_face_detection
    face_x, face_y = driver_data.facePosition
ValueError: not enough values to unpack (expected 2, got 0)
```

`DriverCameraSetupDialog.__init__` calls `set_force_active(True)` on the renderer, but `_draw_face_detection` only guards on `dm_state.faceDetected` and not on the actual length of `driver_data.facePosition` — so the unpack crashes when DM data isn't being published. Workaround: skip onboarding via params (same pattern as `selfdrive/test/helpers.py:21-22`).

### Crash 2 — DEVICE_CAMERAS lookup (the one that matters for this issue)

After skipping onboarding:

```
File "selfdrive/ui/mici/onroad/augmented_road_view.py", line 277, in _update_calibration
  self.device_camera = DEVICE_CAMERAS[(str(sm['deviceState'].deviceType), str(sm['roadCameraState'].sensor))]
KeyError: ('unknown', 'unknown')
```

`common/transformations/camera.py:55-69` covers `("unknown", "ar0231")` and `("unknown", "ox03c10")` for legacy routes ("before deviceState.deviceType was set"), but the CTF route is old enough that **both** `deviceType` and `sensor` are unset, so neither fallback hits.

Adding a single fallback line unblocks the UI to the point described in the original report ("system booting" overlay, video stream visible behind it):

```python
("unknown", "unknown"): _ar_ox_config,  # legacy routes pre-deviceType+sensor publishing
```

Confirmed `--demo` route works as @royjr noted, and the post-onboarding "system booting" persists even after extensive scrubbing — consistent with @sshane's diagnosis that the route uses the deprecated `pandaState` (singular) for ignition.

### Question for maintainers

Given that route regeneration (per @adeebshihadeh) hasn't happened in almost 2y, would a small defensive PR for the `DEVICE_CAMERAS[("unknown", "unknown")]` fallback be welcome? It wouldn't fix the underlying ignition issue, but it would at least convert the hard crash into the documented "system booting" state and keep this issue (and `tools/CTF.md`) in a usable-with-caveats state. Happy to also patch the `facePosition` defensive check if useful.

If you'd rather keep the issue focused on regenerating the route, I understand — please just say the word and I'll hold off on the patches.
