### ISSUE TITLE
ubuntu 24.04: tkinter/pip

### ISSUE THREAD

**Issue by royjr** [commaai/openpilot#32782]
### Describe the bug

On fresh install, ubuntu_setup results in..
```
Already up to date.
python 3.12.4 install ...
Downloading Python-3.12.4.tar.xz...
-> https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tar.xz
Installing Python-3.12.4...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/blah/.pyenv/versions/3.12.4/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.12.4 to /home/blah/.pyenv/versions/3.12.4
update pip
pyenv: pip: command not found

The `pip' command exists in these Python versions:
  3.12.4

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

### OS Version

Ubuntu 24.04

### openpilot version or commit

5c4ea14a3cb7bcb443fbee8c5b1d52c10788c9e8

**Comment by royjr** [comment]
Adding `tk-dev` to `install_ubuntu_dependencies` results in
```
Already up to date.
python 3.12.4 install ...
Downloading Python-3.12.4.tar.xz...
-> https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tar.xz
Installing Python-3.12.4...
Installed Python-3.12.4 to /home/blah/.pyenv/versions/3.12.4
update pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
