### ISSUE TITLE
openpilot not available on lexus ES

### ISSUE THREAD

**Issue by haraschax** [commaai/openpilot#34109]
### Describe the bug

Openpilot not available. Appears to be crashing with:
https://connect.comma.ai/57048cfce01d9625/00000387--bbb12be8af
```
Process card:                                                                   
Traceback (most recent call last):                                              
  File "/usr/local/uv/python/cpython-3.12.3-linux-aarch64-gnu/lib/python3.12/mul
tiprocessing/process.py", line 314, in _bootstrap                               
    self.run()                                                                  
  File "/usr/local/uv/python/cpython-3.12.3-linux-aarch64-gnu/lib/python3.12/mul
tiprocessing/process.py", line 108, in run                                      
    self._target(*self._args, **self._kwargs)                                   
  File "/data/openpilot/openpilot/system/manager/process.py", line 40, in launch
er                                                                              
    mod.main()                                                                  
  File "/data/openpilot/selfdrive/car/card.py", line 274, in main               
    car = Car()                                                                 
          ^^^^^                                                                 
  File "/data/openpilot/selfdrive/car/card.py", line 100, in __init__           
    self.CI = get_car(*self.can_callbacks, obd_callback(self.params), experiment
al_long_allowed, num_pandas, cached_params)                                     
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     
  File "/data/openpilot/opendbc/car/car_helpers.py", line 177, in get_car       
    return get_car_interface(CP)                                                
           ^^^^^^^^^^^^^^^^^^^^^                                                
  File "/data/openpilot/opendbc/car/car_helpers.py", line 154, in get_car_interf
ace                                                                             
    return CarInterface(CP, CarController, CarState)                            
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
  File "/data/openpilot/opendbc/car/interfaces.py", line 95, in __init__        
    self.CS: CarStateBase = CarState(CP)                                        
                            ^^^^^^^^^^^^                                        
  File "/data/openpilot/opendbc/car/toyota/carstate.py", line 31, in __init__   
    can_define = CANDefine(DBC[CP.carFingerprint][Bus.pt])                      
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                      
  File "opendbc/can/parser_pyx.pyx", line 134, in opendbc.can.parser_pyx.CANDefi
ne.__init__                                                                     
RuntimeError: Can't find DBC: 'toyota_nodsu_pt_generated'   
```

### Provide a route where the issue occurs

57048cfce01d9625/00000387--bbb12be8af

### openpilot version

sl_model

**Comment by sshane** [comment]
I had `prebuilt` and `DisableUpdates` on the Lexus, removed all dirty stuff
