### ISSUE TITLE
PyZMQ / ZMQ

### ISSUE THREAD

**Issue by brubakerjeff** [commaai/openpilot#430]
Hi, I'm trying to run Openpilot through Termux on another Android Build (Raspberry PI with Android Things) and getting an error when launching openpilot. I was hoping to get some help. I isolated it to the below.

--- test .py
import zmq
print('do nothing')

$ python2 test.py
Traceback (most recent call last):
File "test.py", line 1, in
import zmq
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/init.py", line 47, in
from zmq import backend
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/init.py", line 40, in
reraise(*exc_info)
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/init.py", line 27, in
_ns = select_backend(first)
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/select.py", line 27, in select_backend
mod = import(name, fromlist=public_api)
File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/cython/init.py", line 6, in
from . import (constants, error, message, context,
ImportError: cannot import name constants
--python3 adds the information below
ImportError: dlopen failed: cannot locate symbol "zmq_strerror" referenced by "/data/data/com.termux/files/usr/lib/python3.7/site-packages/zmq/backend/cython/error.cpython-37m.so"...

This issue is cross linked here 
https://github.com/zeromq/pyzmq/issues/1240
I'm thinking there is some uniqueness in the Tmux/ZMQ Build. Does ZMQ need to be installed somewhere in the system? @geohot @rbiasini  ?

**Comment by brubakerjeff** [comment]
Addressed here https://github.com/zeromq/pyzmq/issues/1240
